 /*
 * problem002.go
 * 
 * Copyright 2014 Stefan Thesing <software@webdings.de>
 * License: WTFPL
 *
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */

package main

import (
    "fmt"
)

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
*/

func use_for_loop(limit int) int {
    sum := 0
    for i := 0; i < limit; i++ {
        sum = check_and_add(i, sum)
    }
    return sum
}

func using_while_loop(limit int) int {
    sum := 0
}

func make_next_fibonacci_pair(number1 = 1, number2 = 2 int) int, int {
    return number2, number2+number1
}


func use_recursion(limit, sum, number int) int {
    if number < limit {
        sum = check_and_add(number, sum)
        return use_recursion(limit, sum, number+1)
    }
    return sum
}

func check_and_add(number int, sum int) int {
    if number % 3 == 0 || number % 5 == 0 {
        sum = sum + number
    }
    return sum
}

func main() {
    fmt.Println("Using a while-loop: ", using_while_loop(4000000))
}
